# Generated by Django 5.2.1 on 2025-05-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
