# Generated by Django 5.2.1 on 2025-05-14 13:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_adminprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='publisher_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='exp_level',
            new_name='preferred_exp_level',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_type',
            new_name='preferred_job_type',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='work_mode',
            new_name='preferred_work_mode',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='apply_to',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='base.interest'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='base.skill'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.skill'),
        ),
        migrations.DeleteModel(
            name='RequiredSkill',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
