# Generated by Django 5.2.1 on 2025-05-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_interest_skill_remove_userinterest_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
