# Generated by Django 5.2.1 on 2025-05-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_user_type_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_date']},
        ),
    ]
